version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'docker'
    directory: '/collector'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      # Group minor+patch updates together
      # Leave major updates and security updates to their own PRs
      minor-updates:
        applies-to: 'version-updates'
        update-types:
          - 'patch'
          - 'minor'
