version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - copyloopvar
    - intrange

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Amund211/flashlight
