name: Check for vulnerable dependencies

on:
  pull_request:
  schedule:
    # Run every day at 4:40 UTC
    - cron: '40 4 * * *'

permissions:
  contents: read

jobs:
  check-vulnerabilities:
    name: Check for vulnerable dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Check for vulnerable dependencies
        run: go tool govulncheck ./...
